---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "borabano.name" . }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ template "borabano.name" . }}
spec:
  selector:
    matchLabels:
      app: quiz-backend
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: quiz-backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: quiz-backend
          image: bora2612b/bora:my-bck
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ template "borabano.name" . }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: quiz-backend
    tier: backend
    track: stable
  type: ClusterIP
status:
  loadBalancer: {}

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "azure-voting-app-redis.fullname" . }}
  namespace: {{ template "azure-voting-app-redis.name" . }}
  labels:
    app: {{ template "azure-voting-app-redis.name" . }}
    chart: {{ template "azure-voting-app-redis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "azure-voting-app-redis.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "azure-voting-app-redis.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          env:
          - name: backend
            value: "quiz-backend"
